### ISSUE TITLE
Joins not appearing in results and making N+1 queries

### ISSUE THREAD

**Issue by bhilst-searshc** [mhellkamp/hyperion-sample#1]
We are running into a few blocking issues that we haven’t been able to resolve.  These same problems appear in the hyperion_sample project, so we don’t have a working example to go from.  We’re hoping you can unblock us.  Note we’re using the current master branch code, not hyperion_2.
1.  GETs on apis with @ManyToOne joins are making N+1 queries to get the related entity.  You can see this in the hyperion_example Customer api.  The Customer entity has a @ManyToOne relationship with Region and I would expect JPA to do an inner join between Customer and Region, but instead it fires a separate query for each region entity.  I tried variations on the @ManyToOne FetchType and added an @JoinType indicator, but it doesn’t make any difference.
2.  Exposing a joined entity isn’t working for us.  In the hyperion_example, the swagger UI shows a Customer.region child entity in the api; however, this doesn’t work in the actual code.  I tried adding Region getter/setters to the Customer class, but that doesn’t make any difference.  There is a custom RegionIdFieldMapper used by the CustomerTranslator, but it doesn’t seem to make any difference if we remove it.

Expected
{
  "page": {
    "start": 0,
    "responseCount": 0,
    "totalCount": 0
  },
  "entries": [
    {
      "id": 0,
      "companyName": "string",
      "contactName": "string",
      "contactTitle": "string",
      "address": "string",
      "city": "string",
      "regionId": 0,
      "postalCode": "string",
      "country": "string",
      "phone": "string",
      "fax": "string",
      "creditRating": "NONE",
      "created": 0,
      "createdBy": "string",
      "modified": 0,
      "modifiedBy": "string",
      "region": {
        "id": 0,
        "regionName": "string",
        "created": 0,
        "createdBy": "string",
        "modified": 0,
        "modifiedBy": "string"
      }
    }
  ]
}

Actual
{
  "page": {
    "start": 1,
    "responseCount": 3,
    "totalCount": 3
  },
  "entries": [
    {
      "id": 1,
      "companyName": "Sears",
      "contactName": "Brian Hilst",
      "contactTitle": "Software Developer",
      "address": "8150 Hansen Rd",
      "city": "Bainbridge Island",
      "regionId": 1,
      "country": "US",
      "phone": "2068557927",
      "fax": "",
      "created": 1446854367659,
      "createdBy": "",
      "modified": 1446854367659,
      "modifiedBy": ""
    },
  ]
}

**Comment by mhellkamp** [comment]
The API is exposing regionId, not the region object itself. It is possible to expose the entire related object but I would strongly recommend against including related objects in the API, just reference them by IDs. Including the related object can be a significant performance hit when you are dealing with large data sets. This gets exacerbated by JPA mapping issues, as you discovered, that can make performance even worse. 

The example mapping was actually a rather bad one, this was really a contrivance to validate being able to query and sort on related objects. I've updated the mapping to explicitly use regionId rather than translating it from the related object mapping. Region is still mapped for querying purposes but is never directly referenced so is never retrieved.
